### ISSUE TITLE
Cannot be added to Godot Engine core

### ISSUE THREAD

**Issue by fire** [Lcbx/GdScript2All#10]
It is unusable for Godot Engine to use GdScript2All in the core. The GdScript2All code has to be rewritten from scratch due to the GPL3 license vs. Godot's MIT license.

**Comment by Lcbx** [comment]
If you wanted to make this addon part of the engine,
it is not possible to just put into core, yes.

Because of the license, because it's in python, because it does not use Godot's internals to parse the gdscript.
Sorry

**Comment by fire** [comment]
I believe gpl cannot allow me to port the meaning of the code either.
