### ISSUE TITLE
Scripts from GDScript Formatter plugin cause PANIC on multi-line conditionals.

### ISSUE THREAD

**Issue by tiggerntatie** [Lcbx/GdScript2All#11]
Code like, for example (which is a common construct used by gdscript formatters to maintain a line-length limit):
```
	if (
		_terminal_pad.length()
		and (
			not buffer_size or (_terminal_buffer[-1] != _terminal_pad)
		)
	):
```
Produces
```
if((_TerminalPad.Length()) && (!buffer_size || (_TerminalBuffer[ - 1] != _TerminalPad)))
{
}
//PANIC! <) :> unexpected at Token(type=')', value=')', lineno=343, index=10613, end=10614)
```
This seems to be responsible for most of the PANICS in my code.

**Comment by Lcbx** [comment]
this was actually a known limitation (stated in the readme)
I fixed it though with latest commit.
Still doesn't keep the newlines in the output though.

Thanks for using the tool :)
