### ISSUE TITLE
Is test cause panics

### ISSUE THREAD

**Issue by ClayZH** [Lcbx/GdScript2All#6]
change the test.gd _"method"_ function in line 32 to below:
```gdscript
func method(param = 5.):
	for k in string_array:
		if not k is String:
			pass
	return val * param
```

get panics:
> consumed: method
consumed: param
consumed: 5.
UpScope 0
emit: <EOL>{
emit: <EOL>  
consumed: k
consumed: string_array
emit: string_array
emit: for(String k : string_array)
UpScope 1
emit: <EOL>  {
emit: <EOL>    
consumed: not
consumed: k
emit: if(
emit: !
emit: k
emit: )
UpScope 2
emit: <EOL>    {
consumed: is
emit: is
emit: ;
consumed: String
emit: String
emit: ;
emit: ;
emit: ;
emit: ;
emit: void test::method(double param)
consumed: :
emit: <EOL>      
emit: //PANIC! <:> unexpected at Token(type=':', value=':', lineno=34, index=640, end=641)<EOL>      
PANIC! <:> unexpected at Token(type=':', value=':', lineno=34, index=640, end=641)
DownScope 3
emit: <EOL>    }
DownScope 2
emit: <EOL>  }
emit: <EOL>  
consumed: return
consumed: val
consumed: *
consumed: param
DownScope 1
emit: <EOL>}
emit: <EOL><EOL>
consumed:  type inference on members
emit: <EOL>
PANIC! <return val * param> unexpected at Token(type='TEXT', value='return', lineno=36, index=651, end=657)

**Comment by ClayZH** [comment]
Thanks for the quick response and hard effort. 
But I still get problem after test on the latest commit, it occurs when the is test as if expression (which I think is the most common use case)
```gdscript
if i is int:
	pass
```
will get (c++):
```c++
    if(i)
    {is;int;;;
        //PANIC! <:> unexpected at Token(type=':', value=':', lineno=30, index=330, end=331)

    }

    //PANIC! <print ( i is int )> unexpected at Token(type='TEXT', value='print', lineno=33, index=341, end=346)
```

**Comment by Lcbx** [comment]
thanks for reporting the bugs and testing the fix !
it should work OK now :)
