### ISSUE TITLE
Keep geting error

### ISSUE THREAD

**Issue by wolfsmith520-github** [Lcbx/GdScript2All#7]
Python version - 3.13
Godot Version - 4.3 Stable Mono
Log 

> [91mUnicodeDecodeError 'gbk' codec can't decode byte 0x86 in position 99: illegal multibyte sequence[0m
  at main.py:70	main
Traceback (most recent call last):
  File "C:\_Project\Godot4\c#test\addons\gdscript2all\converter\main.py", line 176, in <module>
    main()
    ~~~~^^
  File "C:\_Project\Godot4\c#test\addons\gdscript2all\converter\main.py", line 110, in main
    print(f"Converted {to_simple_path(filename)} to {to_simple_path(outname)} ({i+1}/{total})")
                       ~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\_Project\Godot4\c#test\addons\gdscript2all\converter\main.py", line 62, in <lambda>
    to_simple_path = lambda s: f'{s.split(os.path.sep)[-2]}/{os.path.basename(s)}'
                                  ~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

**Comment by Lcbx** [comment]
Hi @wolfsmith520-github, thanks for testing the addon.

from the error msg and personal testing,
the error was caused by some path manipulation failing on scripts located directly in the project root. my bad.

I pushed a fix and it will be available in the asset library shortly.
Have a great day !

**Comment by wolfsmith520-github** [comment]
> Hi @wolfsmith520-github, thanks for testing the addon.
> 
> from the error msg and personal testing, the error was caused by some path manipulation failing on scripts located directly in the project root. my bad.
> 
> I pushed a fix and it will be available in the asset library shortly. Have a great day !

Thank you so much ! And glad to help to improve the addon
