### ISSUE TITLE
Trigger error message and error type on iterator result.

### ISSUE THREAD

**Issue by ForceQuady** [Lcbx/GdScript2All#8]
- Unitialized variable trigger message: TypeError 'NoneType' object is not an iterator.
- Undefined type in iterator, in the result set same type.

Original
```
static func show_list(raw : String) -> String:
	var methods : String # -------- Uninitialize variable, Excpted: ( var methods : String = "" ) for no error message

	var lines : PackedStringArray = raw.split("\n")
	for line in lines:  # --------  Undefined value type
		var idx : int = line.find("(")
		if idx != -1:
			methods += '\n"' + line.substr(0, idx).replace(" ", "") + '",'

	return methods
```
Result
```
String builtins::show_list(String raw)
{
	String methods;

	PackedStringArray lines = raw.split("\n");
	for(PackedStringArray line : lines) // ------ Error: line is String!
	{
		int idx = line.find("(");
		if(idx !=  - 1)
		{
			methods += "\n\"" + line.substr(0, idx).replace(" ", "") + "\",";
		}
	}

	return methods;
}
```

**Comment by ForceQuady** [comment]
Strings with backlash/double backlash like `"\n \\ \" "` trigger panic

Another sintax trigger
#ORIGINAL
```
var bytes : PackedByteArray
# ....
bytes[6] = (bytes[6] & 0x0f) | 0x40
bytes[8] = (bytes[8] & 0x3f) | 0x80
```

#RESULT
```
	bytes[6] = (bytes[6] & 0);x0f;;//PANIC! <) | 0 x40> unexpected at Token(type=')', value=')', lineno=969, index=35717, end=35718)

	{bytes[8] = (bytes[8] & 0);x3f;;//PANIC! <) | 0 x80> unexpected at Token(type=')', value=')', lineno=970, index=35754, end=35755)
```

### UPDATED#1

token begin or, is hanled as OR operation??

#ORIGINAL
`var original_path : String = any_path `

#RESULT
`Variant or;iginal_path;;//PANIC! <: String = any_path> unexpected at Token(type=':', value=':', lineno=286, index=5615, end=5616)`


### UPDATE#2

Indentation of #, can break the code

example
```
        # {Part of code in function}
        # {...}
	var preprocess : bool = false

# {<- Indentation Bug breaker}
        # {Normal continue in the same function}
	if FileAccess.get_file_as_string(path).find("?"):
		preprocess = true
```

#RESULT

- Bug after var preprocess : bool = false
```

	bool preprocess = false;
}

{preprocess = true;
}
```

**Comment by Lcbx** [comment]
> * Unitialized variable trigger message: TypeError 'NoneType' object is not an iterator.

it seems the type resolver expected an assignment no matter what, I can't believe this bug got past me

> Strings with backlash/double backlash like "\n \\ \" " trigger panic

Edit : should be fixed.

> bytes[6] = (bytes[6] & 0x0f) | 0x40

hexadecimal literals were unsupported, added them just for you 😉

> token begin or, is handled as OR operation??

an error in the tokenizer, my bad

> Indentation of #, can break the code

Fixed this using a new solution, though generating code while keeping comments and indentation is a hard problem.
so expect output to not be perfect

Thanks for trying this !
hope it is useful nonetheless 😊

**Comment by ForceQuady** [comment]
Thank you so much,
For the comments, yeah, a quick and dirty solution I once used for a project was to use regular expressions to store line references and clean them up before using the parser.
