### ISSUE TITLE
Python not found error + add a video tutorial

### ISSUE THREAD

**Issue by RakibRyan** [Lcbx/GdScript2All#9]
it just gives me python not found on fedora

**Comment by Lcbx** [comment]
Hello @RakibRyan

Based on what the message says, installing Python 3 should solve problem.

If you need more help :
* the bash command to install Python should be something like `sudo apt-get install python3`
(https://linuxtldr.com/installing-python/)
* If the problem persists, is Python in your PATH environment ? (https://realpython.com/add-python-to-path/)
* the addon tries to call it with the standard `python` alias, is it set up ? (https://stackoverflow.com/questions/35435517/creating-an-alias-for-python3)

Thanks for trying the addon 🙂
(as for making a video tutorial, I can't make one that would work for everyone, and this is less complicated than it looks)

**Comment by RakibRyan** [comment]
Ok managed to get it to work. 

gave me this log not sure if it's a bug. might be helpful. gd & c++ files included too.
Ignoring character '	'
Ignoring character '	'
Ignoring character '	'
Ignoring character '	'
Converted Player/player.gd to Cpp/player (1/1)


[player.zip](https://github.com/user-attachments/files/17847346/player.zip)

**Comment by Lcbx** [comment]
the unexpected logs could have gone into another Issue
(it is unrelated to the python not found  error or  need for tutorial)

there were trailing tabs inside your script (= tabs at the end of a non-empty line)

the parser now silently ignores trailing tabs
and the error message is more detailed when it meets a truly unexpected char

Thanks for trying the addon, have a nice day :)
